### ISSUE TITLE
Paged queries for MsSql2005 fail when they contain a join

### ISSUE THREAD

**Issue by TrevorPilley** [TrevorPilley/MicroLite#357]

**Comment by bobbyross** [comment]
I am sure that you are aware of this, but thought I would provide a work around that I am currently using in order to move forward with a current project.  The issue appears to be when table aliases are used and the PageQuery method of MsSql2005Dialect does not remove those aliases even though they should not be used in the outer query that is generated.
Here is a method that I have added to MsSql2005Dialect.cs
```
public static string ParseAliasedSelect(string select)
        {
            string selectString = select;
            System.Collections.Generic.List<string> columnsOut = new System.Collections.Generic.List<string>();
            
            string[] columns = selectString.Trim().Split(new char[] { ',' });

            for (int i = 0; i < columns.Length; i++)
            {
                string columnString = columns[i].Trim();
                columnString = columnString.Substring(columnString.LastIndexOf(" AS ", StringComparison.CurrentCulture) + " AS ".Length);
                columnsOut.Add(columnString.Substring(columnString.LastIndexOf('.') + 1));
            }

            return string.Join(",", columnsOut.ToArray());
        }
```
The modified the StringBuilder in PagedQuery method in MsSql2005Dialect.cs to use this method in the outer query:
```
var stringBuilder = new StringBuilder(sqlQuery.CommandText.Length * 2)
                .Append("SELECT ")
                .Append(ParseAliasedSelect(sqlString.Select))
                .Append(" FROM")
                .AppendFormat(CultureInfo.InvariantCulture, " (SELECT {0},ROW_NUMBER() OVER(ORDER BY {1}) AS RowNumber FROM {2}{3}) AS {4}", sqlString.Select, orderByClause, qualifiedTableName, whereClause, tableName)
                .AppendFormat(CultureInfo.InvariantCulture, " WHERE (RowNumber >= {0} AND RowNumber <= {1})", this.SqlCharacters.GetParameterName(arguments.Length - 2), this.SqlCharacters.GetParameterName(arguments.Length - 1));
```

I know the final product you create will be much more elegant and better performing, but this served my purposed and has resolved my issues.

**Comment by TrevorPilley** [comment]
@bobbyross, you are correct the column alias also causes a problem - I haven't had much time recently to look into this particular issue but I will try and implement a resolution soon.

For the time being, a possible workaround is to create a view which does the joins and aliasing and then just use the ability to have read-only mapped classes (introduced in MicroLite 5.2 https://microliteorm.wordpress.com/2014/08/08/microlite-5-2-upcoming-features/) to map to the view
