### ISSUE TITLE
Incorrect parameter count detection

### ISSUE THREAD

**Issue by Chimaine** [TrevorPilley/MicroLite#382]
`SqlUtility.GetParameterNames` returns 2 parameter names ( `:` and `:00` ) for the following SQLite query
```SQL
CREATE VIEW IF NOT EXISTS ListIDs_24h AS
SELECT 
  EPC, 
  substr( EPC, 15, 4 ) AS Type, 
  substr( EPC, 19 ) AS ID, 
  strftime( '%Y-%m-%d %H:%M:%S', Timestamp ) AS Timestamp
FROM LogEntries
WHERE Timestamp > datetime( 'now' ) - time( '24:00' )
ORDER BY Timestamp DESC
```
This causes an exception when you try to execute it with `session.Advanced.Execute` because it "misses" 2 parameters. Providing two empty parameters lets the query run without issues or negative effects.

As far as I understand this, the colon is used in some databases like Oracle as an identifier for parameters, but not in others. 

Maybe IDbDriver or ISqlDialect could provide the `GetParameterNames` method to allow for differences.

**Comment by TrevorPilley** [comment]
`SqlUtility` is used because there are times where we need to match/re-number parameters when the `IDbDriver` isn't known. It's also one of the oldest parts of the current code base so I'll review how it's used as I work on 6.2 and see if it's possible to be more dialect specific without duplicating that logic in numerous places.
