### ISSUE TITLE
Move methods from IAdvancedAsyncSession to IAsyncSession

### ISSUE THREAD

**Issue by djanosik** [TrevorPilley/MicroLite#411]
I see there are some great changes coming to version 7.0... so I will try to propose some more. There are useful methods defined on the `IAdvancedAsyncSession` interface. However, the only methods that feel advanced to me is the `UpdateAsync(objectDelta)` and `ExecutePendingQueriesAsync`. All other methods are quite common and I think there is no reason to hide them behind the `IAsyncSession.Advanced` property.

Also there are other changes to consider:

- Changing the `DeleteAsync(type, identifier)` method to accept a generic type parameter. You don't accept classic type parameters anywhere else in public API. It feels inconsistent.

- Renaming `ExecuteScalarAsync` to `ScalarAsync`. It would look more consistent next to methods like `SingleAsync`, `FetchAsync`, etc.

**Comment by TrevorPilley** [comment]
I disagree, I think `ExecuteScalar` and `Execute` are advanced operations - I don't often find myself using them in an ORM centric application because I am usually using `Single`, `Fetch`, `Paged`, `Delete` and `Update`.

Having a `Delete<T>(object identifier)` method rather than the existing `Delete(Type type, object identifier)` makes it harder to use in a reflective use since you would have to generate a dynamic delegate, it's also less clear in my mind what the API is for. In the case of the Delete function, we do only need the Type hence `Type` being a method parameter. If you don't like this as much, you can always create an extension method:

```CSharp
public bool DeleteAsync<T>(this IAsyncSession session, object identifier)
{
    return session.Advanced.Delete(typeof(T), identifier);
}
```
