### ISSUE TITLE
MicroLite Database Object Name Issues

### ISSUE THREAD

**Issue by mixerp** [TrevorPilley/MicroLite#424]
# Insert Problems

Several tables with the exact same name can happily coexist in different schemas. MicroLite does not allow you to specify the

- schema name
- table name
- primary key column name

for `Insert`. This creates problems when you want to bulk-import data from collection of dynamic/expando object.

Similarly, it would be really useful if the `Insert` returned the identifier or null instead of void because it would reduce extra lines of codes. And also useful for bulk-loading scenarios where you could write something like this

```
foreach(....
    imported.Add(session.Insert(poco));
```

# Bug on Delete

Microlite does not allow you specify the

- schema name
- table name
- primary key column name
- primary key value

for `Update` which creates confusion and mistake as well. For example:

```
var customer = session.Single<Customer>(12354);
customer.CustomerId = 23465;
customer.Status = CustomerStatus.Closed;
updated = session.Update(customer);
```

is converted by MicroLite to something like this:

```
UPDATE [dbo].[Customers]
SET [Status] = 0
WHERE [CustomerId] = 23465;
```
instead of this:

```
UPDATE [dbo].[Customers]
SET 
[Status] = 0,
[CustomerId] = 23465
WHERE [CustomerId] = 12354;
```

IMHO, MicroLite should allow overloads for `Insert` and `Delete` methods so that you can tell more about the database objects.

**Comment by TrevorPilley** [comment]
MicroLite is an ORM which is Object Relational Mapper, you create an object with properties and define how that is mapped to a table and columns using the mapping convention. The idea is that you read, insert, update and delete objects.

This keeps the API simple, you shouldn't have to specify every single time you want to insert an object which table to write to etc, that defeats the purpose of single responsibility. By configuring the mapping, MicroLite takes the responsibility so you can do `session.InsertAsync(customer);` instead of having to do `session.InsertAsync(customer, "schema", "customers", "customer_id")`; - if that's what you really want, look at PetaPoco.

MicroLite *does* allow you to specify the schema name, table name and identifier column - that's what the [mapping convention](https://github.com/TrevorPilley/MicroLite/wiki#mapping-classes-to-tables) does which is how you can just do `session.InsertAsync(customer)` from anywhere in your code and not have to specify the table, schema etc every time.

You are using the [Convention Mapping](https://github.com/TrevorPilley/MicroLite/wiki/Convention-Based-Mapping) so you just need to set the convention you want to define these things. The table name by default will be the plural of the class name, the schema by default will be null and the identifier will be whatever the identifier property is mapped as (e.g. `CustomerId` or `Id`) you can see the [default conventions](https://github.com/TrevorPilley/MicroLite/blob/master/MicroLite/Mapping/ConventionMappingSettings.cs#L30).

When you do Insert, MicroLite actually sets the Identifier value in the Identifier property - see [Session.Insert](https://github.com/TrevorPilley/MicroLite/wiki#insert--insertasync).

As far as the update "bug" goes, it's not a bug, MicroLite doesn't allow you to change the ID of an object by modifying the object itself. That's by design, it will update the row using the current state of the object where the pk equals the object identifier.

**Comment by mixerp** [comment]
Thank you for your insightful answer.

I am not absolutely sure when you say `MicroLite does allow you to specify the schema name, table name and identifier column - that's what the mapping convention does` for the cases where we have different tables in different schemas which share only the same name. Could you please suggest how convention-based mapping could be used to map these two tables and these two classes?

```
CREATE TABLE public.users
(
    user_id SERIAL PRIMARY KEY,
    user_name text,
    password text
)
```
and

```
CREATE TABLE office.users
(
    user_id SERIAL PRIMARY KEY,
    user_name text,
    password text,
    role_id int REFERENCES office.roles
    office_id int REFERENCES office.offices
)
```
for
```
namespace Public
{
    public class User
    {
    }
}
```
and

```
namespace Office
{
    public class User
    {
    }
}
```
Reading MicroLite docs, I think I can use attribute mapping for this very special case. I can happily live with that. But when it comes to bulk-upserting data, this approach would not work for my case. I will leave that for some other time.

## Update

Please forgive me for being lazy and not reading the docs properly, could you please show me a way how can I achieve this except for using a method of MicroLite which uses ExecuteNonQuery (sorry I could not find that)?

**Update primary key along with other columns**

```
UPDATE [dbo].[Customers]
SET 
[Status] = 0,
[CustomerId] = 23465
WHERE [CustomerId] = 12354;
```

instead of this

```
UPDATE [dbo].[Customers]
SET [Status] = 0
WHERE [CustomerId] = 23465;
```

I think PetaPoco's way of doing the above simpler, elegant, and less surprising.

My two cents.

**Comment by TrevorPilley** [comment]
If you read the [convention mapping documentation](https://github.com/TrevorPilley/MicroLite/wiki/Convention-Based-Mapping#customizing-conventions) you will see that one of the conventions you can define is `ResolveTableSchema`. By default this doesn't do anything as different databases use different default schemas and you can define your own. However you can specify a function here which will resolve your schema.

You have `namespace Public { public class User { } }` and you want that to map to `TABLE public.users` so you can specify `ResolveTableSchema` to use the namespace of the class as the schema name:

```csharp
Configure.Extensions()
    .WithConventionBasedMapping(
        new ConventionMappingSettings
        {
            ResolveTableSchema = (Type type) => type.Namespace;
        });
```

You can't change the identifier (PK) in MicroLite by changing it on the instance. Personally, I don't think that is something you should ever need to do... If you think you do need to do this and want to use MicroLite, you would need to either use `session.Advanced.ExecuteAsync` or `session.Advanced.UpdateAsync` - however I would suggest that instead of seeing how to "fit" your use case into the framework that you review what it is you are actually doing to see if it is actually the correct thing to do.

**Comment by mixerp** [comment]
I do not know any correct or incorrect way of doing the following in MicroLite because it is not possible.

```
UPDATE [dbo].[Customers]
SET 
[Status] = 0,
[CustomerId] = 23465
WHERE [CustomerId] = 12354;
```
This is 100% valid requirement,

**Comment by TrevorPilley** [comment]
Why do you need to do it at all? I can't comprehend why you would want to alter the PK
