### ISSUE TITLE
How do you handle table Relations/Navigation properties?

### ISSUE THREAD

**Issue by dareenzo** [TrevorPilley/MicroLite#435]
Hi @TrevorPilley,

I generally use EF for my apps and that usually that is fine. But recently I've been developing with Mono in Linux and Mac and although EF is supported it's kinda of heavy for the tasks I want to accomplish. Due to this I sought to Micro ORMs as an alternative and I've been using ServiceStack Ormlite, but this has a 10 table limit for the free version and I cannot go with that, so I'm considering using MicroLite.

I've been through the documentation and I really like the simplicity of the API, but I'm wondering how you handle table relations/ navigation properties. EF and Ormlite for instance provide Attributes that help mapping the relations, so I wonder if Microlite has something similar or if is there a different approach you use for this

**Comment by TrevorPilley** [comment]
In MicroLite, if you have a "relationship" (e.g. a 1-many) between say Customer and Invoice:

    public class Customer
    {
        public int Id { get; set; }
        ...
    }

    public class Invoice
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        ...
    }

The `Invoice` class would have a property to contain the `CustomerId` but no actual `Customer` property, likewise the `Customer` class would not contain an `List<Invoice> Invoices` property.

It is up to the developer to determine when invoices are loaded rather than the framework so you maintain control over what queries are issued and when. Typically if you want to show the customer and invoice details on a single screen/view you would load the customer and the invoices collection using 2 queries:

    var customer = session.SingleAsync<Customer>(customerId);
    var invoices = session.FetchAsync<Invoice>(InvoiceQueries.ForCustomer(customerId));

where InvoiceQueries.ForCustomer is a static method such as:

    public static SqlQuery ForCustomer(int customerId)
    {
        return SqlBuilder.Select("*")
            .From(typeof(Invoice))
            .Where("CustomerId")
            .IsEqualTo(customerId)
            .ToSqlQuery();
    }

You can gain some performance by using the include feature (see the [wiki](https://github.com/TrevorPilley/MicroLite/wiki#include))
